[workspace]

members = [
  "ipfs-api",
  "ipfs-api-backend-actix",
  "ipfs-api-backend-hyper",
  "ipfs-api-examples",
  "ipfs-api-prelude",
  "ipfs-api-versions",
]

[dependencies]
  enum-as-inner = "0.5.1"
